{
  try {
    doRun(indicator);
  }
 catch (  Exception e) {
    LOG.info("Unexpected exception occurred during processing sequential task '" + myTitle + "'",e);
  }
 finally {
    indicator.stop();
  }
}
