{
  try {
    test2();
  }
 catch (  Inner ex) {
  }
}
