{
  try {
    foo();
  }
 catch (  MyException e) {
  }
catch (  MyException1 myException1) {
  }
}
