def abort(self, exception):
    self.cleanup()
    raise exception
